apiVersion: v1
kind: Pod
metadata:
  name: nginx-base
  namespace: default
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
