apiVersion: batch/v1
kind: Job
metadata:
  name: sleep
spec:
  template:
    spec:
      containers:
        - name: sleep
          image: busybox:latest
          command: ["sleep",  "10s"]
      restartPolicy: Never
  backoffLimit: 4
